Controllers/CaesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Test.Models;
using Test.Models.Interfaces;
using Test.Models.ManyToMany;

namespace Test.Controllers
{
    public class CaesController : Controller
    {
        private readonly ICaesRepository _caesRepository;
        private readonly IDonosRepository _donosRepository;
        private readonly ICaesDonosRepository _caesDonosRepository;

        public CaesController(ICaesRepository caesRepository, IDonosRepository donosRepository, ICaesDonosRepository caesDonosRepository)
        {
            _caesRepository = caesRepository;
            _donosRepository = donosRepository;
            _caesDonosRepository = caesDonosRepository;
        }
        [HttpGet]
        public async Task<ActionResult> ToList()
        {
            return View(await _caesRepository.FindAlls());
        }
        [HttpGet]
        public async Task<ActionResult> Insert()
        {
            List<Donos> list = await _donosRepository.FindAlls();
            ViewBag.Donos = list.Select(x => new SelectListItem(x.Nome, x.Id.ToString()));
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Insert(int dono, Caes caes)
        {
            if (!ModelState.IsValid)
            {
                List<Donos> list = await _donosRepository.FindAlls();
                ViewBag.Donos = list.Select(x => new SelectListItem(x.Nome, x.Id.ToString()));
                return View();
            }

            await _caesRepository.Insert(caes);

            await _caesDonosRepository.Insert(new Models.ManyToMany.CaesDono { CaesId = caes.Id, DonosId = dono });

            return RedirectToAction(nameof(ToList));
        }
        [HttpGet]
        public async Task<ActionResult> Update(int id)
        {
            return View(await _caesRepository.FindById(id));
        }
        [HttpPost]
        public async Task<ActionResult> Update(Caes caes)
        {
            if (!ModelState.IsValid) return View();

            await _caesRepository.Insert(caes);

            return RedirectToAction(nameof(ToList));
        }
        [HttpGet]
        public async Task<ActionResult> Delete(int id)
        {
            List<CaesDono> rs = await _caesDonosRepository.FindByCaes(id);
            if (rs.Count() == 0) return BadRequest();

            foreach (var item in rs)
            {
                await _caesDonosRepository.Remove(item.CaesId, item.DonosId);
            }
            await _caesRepository.Remove(id);
            return RedirectToAction(nameof(ToList));
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Test</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ToList">Donos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Caes" asp-action="ToList">Caes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Test - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>